### ISSUE TITLE
Redesign the whole process of downloading and getting started with Scala

### ISSUE THREAD

**Issue by soc** [soc/scala-lang#16]
Currently, this is a complete trainwreck:
- We tell people to download something which is completely useless after 5 minutes.
- We don't tell people about our hidden dependency on the JVM/JDK, and don't help them to set it up.
- There are too many confusing options in general, and no explanation why someone should pick one over another.

Minimal requirement: **There should be one binary that deals with installing a JDK, downloading SBT, and bootstrapping the rest of Scala.**

**Comment by povder** [comment]
@soc You probably was trying to figure out how to approach creating this one binary thing that deals with installing a JDK etc. Have you come to any conclusions? Are there some blocker problems regarding licensing or something? I'm considering contributing in this area.

**Comment by soc** [comment]
@povder I have a working prototype (lots of missing options and functionality, Linux-only) here: https://github.com/soc/sbs.

I wrote a bit about the current status here: https://github.com/soc/sbs/issues/1
