### ISSUE TITLE
Clarify get-scala goal/contribution opportunities

### ISSUE THREAD

**Issue by DaniRey** [soc/scala-lang#19]
Add an "about" link to the top-level navigation, to describe why get-scala.org exists and what it's goals are. Copy the "about get-scala.org" content to a separate chapter in the readme.

Split the contribution page in to two sections
- contributions to Scala
- contributions to get-scala.org

Describe what and how people can contribute to get-scala.org. Link "about" <-> "get-scala.org contributions"

**Comment by soc** [comment]
Great idea, thanks!

**Comment by soc** [comment]
I wrote http://get-scala.org/about today, but I realized that we had this ticket only right now. At least there is some content, might make it easier to split and reorganize things ... :-)
