### ISSUE TITLE
How to start a Scala project using a buildtool

### ISSUE THREAD

**Issue by DaniRey** [soc/scala-lang#24]
Everyone uses buildtools nowadays, Therefore I think a beginner documentation should also include a minimal builtool setup. 

I just organized a small workshop in my company. To do so, I created a minimal setup for Maven (https://github.com/DaniRey/scala_maven_init) and SBT (https://github.com/DaniRey/scala_sbt_init). These two repositories may be used as inspiration for the documentation of a minimal Scala project setup with various buildtools. I think Maven, SBT and Gradle would be a good start.

**Comment by soc** [comment]
You are right! I am hoping to streamline this with https://github.com/soc/scala-lang/issues/16, using https://github.com/soc to handle everything from initial OpenJDK setup to calling `sbt new`. Nevertheless, there should be some examples/documentation available

**Comment by DaniRey** [comment]
Happy to see https://github.com/soc/sbs taking shape, but it can't replace documentation. I might find some time in December to create a pull-request for this. But it would be good to decide where it should be on the page.
I think the prominent download teaser should be removed from the homepage. There should rather be a pointer to a "getting started" chapter.
