### ISSUE TITLE
spec code examples are broken

### ISSUE THREAD

**Issue by sschaef** [soc/scala-lang#4]
Not all code examples are correctly displayed. For example in this section: http://get-scala.org/documentation/specification/06-expressions.html#expression-typing

The code example is shown as:
```
$T$ forSome { type $t_1[\mathit{tps}\_1] >: L_1 <: U_1$; $\ldots$; type $t_n[\mathit{tps}\_n] >: L_n <: U_n$ }.
```

**Comment by soc** [comment]
I believe this has been fixed. Please reopne if I'm mistaken.
