### ISSUE TITLE
Show same header everywhere

### ISSUE THREAD

**Issue by sschaef** [soc/scala-lang#6]
The [index.html](http://get-scala.org/index.html) shows a different header than all other sites. If one clicks on one of the links in the header, for example `documentation`, the mouse may select `downloads` afterwards because the position of the header is slightly different.

But that is just a minor issue.

**Comment by soc** [comment]
Thanks! Not sure I can do much about it given all the dynamic resizing, but I'll keep it in mind when I touch this the next time!

**Comment by soc** [comment]
Ok, got it down to a small offset, is this fine now?

**Comment by sschaef** [comment]
Still not perfect but good enough for me. ;)

**Comment by soc** [comment]
Thanks!
